### ISSUE TITLE
A new jenkins job is kindly requested for drlx-parser repository in kiegroup

### ISSUE THREAD

**Issue by tarilabs** [kiegroup/kie-jenkins-scripts#69]

**Comment by psiroky** [comment]
We will need at least `deploy_jop`, `pr_job` and `downstream_pr_job`.

**Comment by tarilabs** [comment]
repo kiegroup/drlx-parser is a fork of an upstream project (also available on github and nexus) called javaparser.

It is composed of:
```
[INFO] Reactor Build Order:
[INFO] 
[INFO] javaparser-parent
[INFO] javaparser-core
[INFO] javaparser-testing
[INFO] javaparser-core-generators
[INFO] javaparser-metamodel-generator
[INFO] drlx-parser
```

Please notice the last module `drlx-parser` is introduced by us, and it's an uber jar.

We locally use `mvn clean install` and works without a problem.

However, when on Jenkins, we would need only the module `drlx-parser` to be published.

This is because from drools we use only internally the module `drlx-parser` which is an uberjar of the whole forked project and our own extension.
The module `drlx-parser` also shades the package names to avoid collisions; this allows end-users to have in their dependencies drools and upstream-javaparser without a problem.

How can we get of only the module `drlx-parser` to be published?
If that is not possible, what could be an alternative solution?

Thanks in advance
/cc @mariofusco

**Comment by mbiarnes** [comment]
Do we need this for master and 7.3.x?
Is kiegroup/drlx-parser synced with https://github.com/javaparser/javaparser?

**Comment by psiroky** [comment]
My guess would be only for master.
