### ISSUE TITLE
Add jobs for new kie-soup repo

### ISSUE THREAD

**Issue by psiroky** [kiegroup/kie-jenkins-scripts#74]
We will need deploy and PR jobs for this new repo: https://github.com/kiegroup/kie-soup. It is supposed to be built _before_ uberfire.

**Comment by mbiarnes** [comment]
@psiroky 
questions..:
1. master and 7.3.x?
2. errai, uberfire and dashbuilder (build and deployed before kie are also released. Has kie-soup a release cycle?
  2a. Does it only apply to kieAlBuild daily jobs or also to the kieRelease jobs?
  2b. Is this also as branch needed for gerrit?
  2c. I assume this kie-soup rep is needed for community and for prod?

**Comment by psiroky** [comment]
1. Only master
2. Even though kie-soup has the same version as other KIE projects, it needs to be built _before_ uberfire.
2a. yes, applies to basically all jobs
2b. not sure I understand the question. There is no new branch needed. The repo will need to be part of the prod builds, but only when we actually start building the prod from master (which probably won't be for some time).
2c. yes

**Comment by psiroky** [comment]
Argh, I'll leave this open for now, as we need to process https://github.com/kiegroup/kie-jenkins-scripts/pull/77

**Comment by psiroky** [comment]
This seems to have been done some time, but we likely just forgot to close it. Closing now.
